services:
  carmind-frontend:
    build:
      context: .
    ports:
      - "PUT_YOUR_PORT_HERE:4173"
    environment:
      - VITE_BASE_URL=PUT_YOUR_BACKEND_URL_HERE
      - VITE_NOTIFICATION_URL=PUT_YOUR_FRONTEND_URL_HERE
      - VITE_PUBLIC_VAPID_KEY=PUT_YOUR_PUBLIC_VAPID_KEY_HERE
      